### ISSUE TITLE
work on dart ?

### ISSUE THREAD

**Issue by gcxfd** [TinoGuo/r_crypto#22]
![image](https://user-images.githubusercontent.com/69608605/119740187-0b6dc280-beb6-11eb-898e-ccb22c7cbf58.png)
```

Because rmw depends on r_crypto any which requires the Flutter SDK, version solving
  failed.
```

**Comment by TinoGuo** [comment]
@gcxfd which version of flutter you used? can u share your pubspec.yaml?

**Comment by TinoGuo** [comment]
no more response, closed it
